### ISSUE TITLE
Exception when trying to use as a service

### ISSUE THREAD

**Issue by Pathaleon** [birkett/CloudFlare-DDNS-Updater#6]
I got this error thrown in the event log when I tried to run the program as a service.

System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Net.Connection.CompleteStartConnection(Boolean async, HttpWebRequest httpWebRequest)
   at System.Net.Connection.CompleteStartRequest(Boolean onSubmitThread, HttpWebRequest request, TriState needReConnect)
   at System.Net.Connection.SubmitRequest(HttpWebRequest request, Boolean forcedsubmit)
   at System.Net.ServicePoint.SubmitRequest(HttpWebRequest request, String connName)
   at System.Net.HttpWebRequest.SubmitRequest(ServicePoint servicePoint)
   at System.Net.HttpWebRequest.GetResponse()
   at CloudFlareDDNS.CloudFlareAPI.webRequest(Method MethodType, String szUrl, String szData)

It works fine if I run it manually just not as a service!

**Comment by birkett** [comment]
I'll investigate.
Does this happen immediately after starting the service, or after a while?

**Comment by Pathaleon** [comment]
It happens immediately.

**Comment by birkett** [comment]
I'm struggling to reproduce this.
Can you please confirm how the service was installed, and that the GUI shows the correct configuration?

**Comment by ThatStevensGuy** [comment]
I am also experiencing this. Windows 7 x64. You try to install the service and it crashes immediately.

**Comment by birkett** [comment]
I still haven't been able to reproduce this.
Does the GUI show the correct configuration and work fine?

When installing the service, what account did you install it as?

**Comment by ThatStevensGuy** [comment]
The GUI works perfectly. When it prompts for the user account I entered my user account? I had never seen that prompt before so I'm just guessing.

**Comment by birkett** [comment]
OK, that's fine.
Could you please try the vTest binary on the releases page. It is the same as the stable release, with additional debugging support. It will generate a rather large memory dump file when it crashes.

If you could upload that memory dump and link me to it - it would be appreciated.

**Comment by ThatStevensGuy** [comment]
I have just seen that version now. I've archived the dump and put it on my drive.

https://drive.google.com/file/d/0B6kcOugQrib7ZFdQQVZHSVg4VzA/view?usp=sharing

**Comment by birkett** [comment]
Thanks for that.
Are you sure that you was running "CloudFlareDDNS.exe /install" from an Administrator command prompt? (Start -> Command Prompt -> Right Click -> Run as Administrator).

I have looked at the memory dump, and have reproduced a crash, when running from a standard prompt.

**Comment by ThatStevensGuy** [comment]
Yes I am running the command prompt as an administrator.

**Comment by brendangilmore** [comment]
I was experiencing the same problem and was about to confirm it, I then found a solution of formatting the username as .\username rather than just username
Once I did that the service installed successfully. 
From:
http://stackoverflow.com/questions/2205744/error-in-installing-windows-service-developed-in-net
